---
language: r
r_binary_packages:
  - tidyverse
  - devtools
  - pkgdown
before_script: Rscript -e 'devtools::document()'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
